# Generated by Django 5.0.7 on 2024-08-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_comment_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
